language: node_js
node_js:
  - 'lts/*'

cache:
  yarn: true

script:
  - yarn test --coverage
  - yarn build

deploy:
  on:
    branch: master
  skip_cleanup: true
  provider: firebase
  token:
    - $FIREBASE_TOKEN
# deploy:
#   on:
#     branch: master
#   provider: s3
#   access_key_id: "YOUR AWS ACCESS KEY"
#   secret_access_key: "YOUR AWS SECRET KEY"
#   bucket: "S3 Bucket"
#   skip_cleanup: true
#   local_dir: build
#   detect_encoding: true
#   default_text_charset: 'utf-8'
#   acl: public_read

# NOTE: use docker to install travis CLI to encrypt aws keys
#       https://hub.docker.com/r/sanjose/travis-encrypt
